# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.java.home=C:\\Program Files\\Eclipse Adoptium\\jdk-21.0.9.10-hotspot
# Fabric Properties on https://modmuss50.me/fabric.html
#minecraft_version=1.19.4
#yarn_mappings=1.19.4+build.2
#loader_version=0.14.22
# Mod Properties
mod_version=0.1.2
maven_group=back_in_classic
archives_base_name=back_in_classic
# Dependencies

minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.16.5
fabric_version=0.105.0+1.21.1